### ISSUE TITLE
using same pagingController with two different screen 

### ISSUE THREAD

**Issue by heshesh2010** [EdsonBueno/infinite_scroll_pagination#300] opened 2023-11-13 21:35 UTC
Hi , 
I have screen has two tabs each tab has some paginated data from api , so I'm going to use same pagingController with two tabs 

but when I switch from tap to other I call pagingController.refresh() 
but I see the data is duplicated and fetchPage is called twice . 

so how I could handle this scenario

**Comment by Ramsay99** [comment] 2023-12-09 17:15
i would like to test something on your project, what is your repo name if its public

**Comment by clragon** [comment] 2024-02-19 19:47
Duplicate of #148

**Closed by clragon** 2024-02-19 19:47 UTC
