### ISSUE TITLE
Appending items from both sides of the list

### ISSUE THREAD

**Issue by akbarpulatov** [EdsonBueno/infinite_scroll_pagination#165] opened 2022-01-27 18:20 UTC
How can I append new items to the list from both sides? For example, for messaging app, there is a need for appending items as from the top as history and from the bottom as new messages. How can one achieve this behavior?

**Comment by clragon** [comment] 2022-01-30 22:52
duplicate of #56

**Closed** 2023-03-02 22:10 UTC
