### ISSUE TITLE
What is a proper way to scroll and cache on both sides (top/bottom or left/right)?

### ISSUE THREAD

**Issue by iostriz** [EdsonBueno/infinite_scroll_pagination#158] opened 2021-12-21 20:35 UTC
Imagine you have endless list and you're placed in the middle.
Going left moves to the past, going right to the future.
I would like to lazily load items on both sides.
Is that possible?

**Comment by clragon** [comment] 2021-12-28 16:31
this issue is a duplicate of #56

**Closed** 2022-01-15 18:40 UTC
