### ISSUE TITLE
[Question] Animating Items in PagedListView on Add/Remove

### ISSUE THREAD

**Issue by tsomone** [EdsonBueno/infinite_scroll_pagination#308] opened 2024-01-17 05:01 UTC
I want to implement item animations when adding or removing items from the list. Currently, the items are loaded and displayed seamlessly, but I'd like to add a fade-in effect for newly added items and a fade-out effect when removing items. Any guidance or code snippets on how to achieve this animation behavior would be greatly appreciated! Thank you.

**Comment by clragon** [comment] 2024-02-17 21:47
Its posible to make your own variant of a paged widget by following the source code of the existing variants. 
By using an animated grid you can achieve those desired animations.

**Comment by clragon** [comment] 2024-02-19 19:49
Duplicate of #21

**Closed by clragon** 2024-02-19 19:49 UTC
Labels: feature
