### ISSUE TITLE
Keeping scroll offset between tabs/pages

### ISSUE THREAD

**Issue by changlan** [EdsonBueno/infinite_scroll_pagination#112] opened 2021-06-27 09:03 UTC
Hello, I was unable to get `PagedListView.separated` to keep scroll offsets for each list after switching between tabs/pages. Might be related to #97. Here is a minimal example to reproduce:

```dart
import 'package:flutter/material.dart';
import 'package:infinite_scroll_pagination/infinite_scroll_pagination.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final controller = DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          title: Text('Test'),
          bottom: TabBar(
            isScrollable: true,
            tabs: [
              Tab(text: 'A'),
              Tab(text: 'B'),
            ],
          ),
        ),
        body: TabBarView(
          children: [
            PagedTopicListView(id: 0),
            PagedTopicListView(id: 1),
          ],
        ),
      ),
    );
    return controller;
  }
}

class PagedTopicListView extends StatefulWidget {
  PagedTopicListView({required this.id, Key? key}) : super(key: key);

  final int id;

  @override
  _PagedTopicListViewState createState() => _PagedTopicListViewState();
}

class _PagedTopicListViewState extends State<PagedTopicListView> {
  final _pagingController = PagingController<int, String>(firstPageKey: 0);

  @override
  void initState() {
    _pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
    super.initState();
  }

  Future<void> _fetchPage(int pageKey) async {
    if (pageKey < 100) {
      _pagingController.appendPage(
          new List<int>.generate(10, (index) => index + pageKey)
              .map((e) => e.toString())
              .toList(),
          pageKey + 10);
    } else {
      _pagingController.appendLastPage([]);
    }
  }

  @override
  void dispose() {
    _pagingController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => RefreshIndicator(
        child: PagedListView.separated(
          key: PageStorageKey(widget.id),
          pagingController: _pagingController,
          builderDelegate: PagedChildBuilderDelegate<String>(
            itemBuilder: (context, item, index) => Text(item),
          ),
          separatorBuilder: (context, index) => const Divider(),
        ),
        onRefresh: () => Future.sync(
          () => _pagingController.refresh(),
        ),
      );
}
```

Desired behavior: Scroll down in Tab A, switch to Tab B, then switch back, The app should return to Tab A's previous scroll offset.

Actual: After switching back to Tab A, the app returns to the top of the list.

**Comment by Sahil-Colco** [comment] 2021-06-28 14:40
Same issue need help @EdsonBueno .

**Comment by EdsonBueno** [comment] 2021-06-29 11:44
Hi @changlan .
What happens if you switch your `PagedListView` with a regular `ListView`?

**Comment by changlan** [comment] 2021-06-29 20:46
`ListView` works correctly: it remembers the last scroll offset and restores the offset after switching back.

**Comment by EdsonBueno** [comment] 2021-06-30 10:41
@changlan No, your sample doesn't remember the last scroll offset when you use a regular `ListView`.
Example: 
```dart
@override
  Widget build(BuildContext context) => RefreshIndicator(
        child: ListView.separated(
          itemBuilder: (ctx, item) => Text('$item'),
          separatorBuilder: (context, index) => const Divider(),
          itemCount: 1000,
        ),
        onRefresh: () => Future.sync(
          () => _pagingController.refresh(),
        ),
      );
```
That tells you that the problem is actually unrelated to the package. [This](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/31#issuecomment-748028524) is the solution to your problem. At least it worked on your sample project!

@Sahil-Colco there's probably something else wrong with your code. When you add `AutomaticKeepAliveClientMixin` to @changlan's example it works perfectly.

Thank you both.
I'm closing the issue for now.

**Closed by EdsonBueno** 2021-06-30 10:41 UTC

**Comment by changlan** [comment] 2021-07-01 03:09
Hi @EdsonBueno, I used the following example and it actually remembered the last scroll offset:

```dart
class PagedTopicListView extends StatefulWidget {
  PagedTopicListView({required this.id, Key? key}) : super(key: key);
  final int id;

  @override
  _PagedTopicListViewState createState() => _PagedTopicListViewState();
}

class _PagedTopicListViewState extends State<PagedTopicListView> {
  final _pagingController = PagingController<int, String>(firstPageKey: 0);

  @override
  void initState() {
    _pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
    super.initState();
  }

  Future<void> _fetchPage(int pageKey) async {
    if (pageKey < 100) {
      _pagingController.appendPage(
          new List<int>.generate(10, (index) => index + pageKey)
              .map((e) => e.toString())
              .toList(),
          pageKey + 10);
    } else {
      _pagingController.appendLastPage([]);
    }
  }

  @override
  void dispose() {
    _pagingController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => RefreshIndicator(
        child: ListView.separated(
          key: PageStorageKey(widget.id),
          itemBuilder: (context, index) => Text(index.toString()),
          itemCount: 100,
          separatorBuilder: (context, index) => const Divider(),
        ),
        onRefresh: () => Future.sync(
          () => _pagingController.refresh(),
        ),
      );
}
```

The difference seems to be `key: PageStorageKey(widget.id)`. Can you test again before closing the issue? Thanks.

**Comment by EdsonBueno** [comment] 2021-07-03 15:35
I already posted the solution to your problem @changlan .
Have you tried using `AutomaticKeepAliveClientMixin`?
