### ISSUE TITLE
Pages fetched all at once and each page two times

### ISSUE THREAD

**Issue by emiguzik** [EdsonBueno/infinite_scroll_pagination#47] opened 2021-02-08 15:53 UTC
Hi,
I'm working on pagination for my app (Flutter for web) and I noticed two issues:
- all pages are fetched at once, not on the scroll
- every page is requested twice (`_fetchPage` is called two times for each `pageKey`)

What is interesting, the number of items as a result is correct, no duplications. So for end user it's not really visible, and still better than waiting for one huge request, but would be nice to get this working properly. Might it be different behavior for `PagingController` in web?

Code:
```
class IssuesBody extends StatefulWidget {
  const IssuesBody();

  @override
  _IssuesBodyState createState() => _IssuesBodyState();
}

class _IssuesBodyState extends State<IssuesBody> {
  static const int _pageSize = 15;
  final IssuesRepository _issuesRepository = locator<IssuesRepository>();

  final PagingController<int, IssuesDetails> _pagingController = PagingController<int, IssuesDetails>(firstPageKey: 0);

  @override
  void initState() {
    _pagingController.addPageRequestListener((int pageKey) {
      _fetchPage(pageKey);
    });
    super.initState();
  }

  Future<void> _fetchPage(int pageKey) async {
    try {
      final IssuesResponse issuesResponse = await _issuesRepository.fetchIssues(pageKey, _pageSize);
      final List<IssuesDetails> newItems = issuesResponse.results;
      final bool isLastPage = newItems.length < _pageSize;
      if (isLastPage) {
        _pagingController.appendLastPage(newItems);
      } else {
        final int nextPageKey = pageKey + 1;
        _pagingController.appendPage(newItems, nextPageKey);
      }
    } catch (error) {
      _pagingController.error = error;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        _buildIssuesHeader(),
        const SizedBox(height: 30),
        PagedListView<int, IssuesDetails>(
          shrinkWrap: true,
          pagingController: _pagingController,
          builderDelegate: PagedChildBuilderDelegate<IssuesDetails>(
            itemBuilder: (BuildContext context, IssuesDetails issuesBuilding, int index) {
              return IssuesBuildingCard(building: issuesBuilding);
            },
          ),
        ),
      ],
    );
  }

  Widget _buildIssuesHeader() {
    // not relevant, simple widget
  }

  @override
  void dispose() {
    _pagingController.dispose();
    super.dispose();
  }
}
```

**Comment by EdsonBueno** [comment] 2021-02-09 09:28
Hi @emiguzik.
This doesn't happen on mobile apps, and your code looks correct, so it might be something with web.
One thing I noticed (which shouldn't be the problem), is that you're using `shrinkWrap: true`. My guess is that you're using it because this widget is being used inside another scrollable widget.
When that is the case (scrollable widgets inside scrollable widgets, both in the same direction) you should work with [Flutter Slivers](https://medium.com/flutter/slivers-demystified-6ff68ab0296f). This package has a Sliver version of a paginated list, which is `PagedSliverList`.
Please, try seeing if that is the problem, and if it isn't, can you provide me a toy project reproducing the issue so that I can help you with it?

**Comment by Martibis** [comment] 2021-02-11 13:13
I do think shrinkWrap: true is causing issues here (just had a very similar problem, it just keeps loading more and more pages, so it seems it keeps triggering the pageRequestListener). I'll investigate some more and will update.

**Comment by Martibis** [comment] 2021-02-11 13:35
Just tried with slivers and had the same issues (granted I have barely any experience with slivers, so I might have messed something up)

**Comment by Martibis** [comment] 2021-02-11 13:52
Got it to work for me, this is what (the possibly relevant parts of) my widget tree looks like now in case it helps @emiguzik 

Scaffold -> SafeArea -> Column -> Expanded ->CustomScrollView -> slivers: [SliverList, Builder -> BlocListener -> PagedSliverList]

**Comment by EdsonBueno** [comment] 2021-02-11 13:55
Thank you so much @Martibis. The nested scrolling views kill the lazy effect.
I'm closing this issue for now, but feel free to reopen it @emiguzik.

**Closed by EdsonBueno** 2021-02-11 13:55 UTC

**Comment by Martibis** [comment] 2021-02-11 15:40
Ah, I did find another issue, it seems to call the pageRequestListener twice every time now (e.g.: first time it gets 2 pages, scroll to the bottom, it gets another 2 pages).
