### ISSUE TITLE
[Question] Disable Automatic Next Page Load

### ISSUE THREAD

**Issue by avishail** [EdsonBueno/infinite_scroll_pagination#309] opened 2024-01-18 07:06 UTC
Is it possible to replace the "automatic next page load" functionality with a "load next page" button so the next page load will be driven by explicit user action?

I have a use-case where loading the next page is very expensive and I want this to happen only if the user really wants to see the next page.

Thanks!

**Comment by nandakista** [comment] 2024-02-05 08:30
I have the same issue

**Comment by clragon** [comment] 2024-02-19 20:07
Duplicate of #177

**Closed by clragon** 2024-02-19 20:07 UTC
