### ISSUE TITLE
manually trigger the next page items request 

### ISSUE THREAD

**Issue by jagmohanJelly** [EdsonBueno/infinite_scroll_pagination#191] opened 2022-05-02 11:22 UTC
like i want the next API call to be executed after a button click or on the bases of user scroll extent, now it automatically calls the next items request with any action

**Comment by masreplay** [comment] 2023-02-12 20:55
@jagmohanJelly any idea how to implement this?

**Comment by EdsonBueno** [comment] 2023-08-17 20:49
Duplicate of https://github.com/EdsonBueno/infinite_scroll_pagination/issues/177

**Closed by EdsonBueno** 2023-08-17 20:49 UTC
