### ISSUE TITLE
When an initial page is provided to the widget to refresh it, and the second page was the last page loaded beforehand, the second page will not be requested when it should.

### ISSUE THREAD

**Issue by hacker1024** [EdsonBueno/infinite_scroll_pagination#16] opened 2020-11-05 13:04 UTC
~~The data I'm paginating can occasionally change on the server. If I detect this has happened while paginating, I must invalidate the data and clear everything.~~

~~Basically, I'm doing this (simplified with state management removed):~~

> ```dart
> Future<void> load() async {
>   final newPage = await loadData()
>   if (oldPage.isInvalid(newPage) {
>     _pagingController.value = PagingState(
>       nextPageKey: 0,
>       itemList: null,
>       error: null,
>     );
>   } else {
>     _pagingController.value = PagingState(
>       nextPageKey: newData.length,
>       itemList: newData.items,
>     );
>   }
> }
> ```

~~This load function is called by a listener added with `addPageRequestListener`.~~

~~The above code, however, doesn't usually work. Instead, the widget will just stop updating, showing the loading indicator at the bottom of the old page indefinitely.~~

**Comment by EdsonBueno** [comment] 2020-11-05 13:53
Try replacing the code inside the `if` with `_pagingController.refresh()`. Tell me if it works, please!

**Comment by hacker1024** [comment] 2020-11-06 00:03
Unfortunately, I can't use `_pagingController.refresh()` here because the new request is made by my state management, which calls `load()` again. As my code duplicates the refresh code without the duplicate request, however, I doubt using it will fix the issue. I'll make a sample project.

**Comment by hacker1024** [comment] 2020-11-06 06:33
This issue was too tough to replicate, but I've diagnosed the cause.
It's not about the loading state like I originally thought, but instead about `_lastFetchTriggerIndex`.

When I refresh my list, I download the first page again manually, and then provide it to the `PagingController`.
As the widget never requests the first page itself, the status goes straight from completed to ongoing, and [this code](https://github.com/EdsonBueno/infinite_scroll_pagination/blob/4a8c8e1561e3ea98ccefc93f11565da0285c3574/lib/src/ui/paged_sliver_builder.dart#L181) never runs. `_lastFetchTriggerIndex` is never reset.

As a result, when the second page was the last page that was loaded _before_ refreshing, it will not be requested again _after_ refreshing.

This only applies to the second page specifically, because if a later page was the last page loaded, the scond page would load before it and overwrite `_lastFetchTriggerIndex`.

Do you have any ideas of how to fix this?

**Comment by EdsonBueno** [comment] 2020-11-06 13:48
@hacker1024 Can you test it with the code on the `bugfix/page-request-trigger-index` branch?
If it works I'll release it.

**Comment by hacker1024** [comment] 2020-11-08 02:20
Unfortunately, it's causing some problems. I need to debug.

**Comment by hacker1024** [comment] 2020-11-08 03:10
Okay, here's what's happening now:

1) User opens screen, first page loads.
2) Page is modified on the server.
3) User scrolls down, `_pageRequestTriggerIndex` is set to the next page's value, the next page tries to load and fails. Error text is given to the paging controller instead.
4) User refreshes the page, which results in the first page being downloaded and provided to the controller.
5) User scrolls down. The `newTriggerIndex` is the second page's value, which is compared to `_pageRequestTriggerIndex` - but this has not changed since refreshing, and has remained set to the second page's value. `_hasRequestedPageForTriggerIndex` remains `true`, and the second page is not requested when it should be.

**Comment by EdsonBueno** [comment] 2020-11-12 09:56
Hi @hacker1024 .
I'm sorry for the delay. I'm on a trip right now and will be back in 10 days or so.
As soon as I'm back, I'll help you with that.
Thank you!

**Comment by EdsonBueno** [comment] 2020-11-23 10:16
Hi @hacker1024 . I'm back!
Please, can you test it again with the code on `bugfix/page-request-refactor`?
I also changed that code from your merged PR. So, it would be great if you could also test [this](https://github.com/EdsonBueno/infinite_scroll_pagination/issues/12).
Thank you! I'm waiting your feedback.

**Comment by hacker1024** [comment] 2020-11-24 02:38
Thanks, I'll test it when I get the next opportunity (hopefully later today).

**Comment by awnigharbia** [comment] 2020-11-24 14:38
Hey @EdsonBueno , My issue was solved with `bugfix/page-request-refactor` branch.

**Comment by EdsonBueno** [comment] 2020-11-30 10:06
@hacker1024 any news on this?

**Comment by verkit** [comment] 2020-12-10 19:06
Hi @EdsonBueno, I have a problem when use `_pagingController.refresh()`
this function should work to clear the data and then reload the data it gets, it's right?.
If so, what happened to my project was not the case, but instead the data increased and did not empty the previous data.

I used this [example](https://github.com/EdsonBueno/infinite_scroll_pagination/blob/master/example/lib/presentation/search_grid_bloc/character_sliver_grid.dart) on my project.

**Comment by EdsonBueno** [comment] 2020-12-10 20:51
@verkit Can you share a toy project reproducing the issue? Since the example doesn't have the same bug, it's probably something on your end.
As this is not related to this issue, please send me via [chat](https://gitter.im/infinite_scroll_pagination/community).
Thank you so much!

**Comment by EdsonBueno** [comment] 2020-12-14 12:42
@awnigharbia and @hacker1024 
I finally released this fix on version 2.2.3!
Thank you for your patience.

**Closed by EdsonBueno** 2020-12-14 12:42 UTC
