### ISSUE TITLE
BUG pageController addPageRequestListener called twice (original example)

### ISSUE THREAD

**Issue by fullflash** [EdsonBueno/infinite_scroll_pagination#136] opened 2021-09-21 01:37 UTC
tested example was taken from github.

addPageRequestListener called twice.

_pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });

https://github.com/EdsonBueno/infinite_scroll_pagination/blob/b2100b42dfad3edab535553823c409aa83bac716/example/lib/presentation/pull_to_refresh/character_list_view.dart

**Comment by EdsonBueno** [comment] 2021-10-17 19:50
Hi @fullflash.
I wasn't able to reproduce the issue. Can you check whether the `pageKey` was the same for the two calls?
Sometimes in smaller screens the listener can be called twice (once for the first page and once for the second) if the first page can't fulfill the entire screen and still leave some items hidden.

I'll close the issue for now since I couldn't reproduce it, but feel free to continue the discussion. If we find this to be a real issue we'll reopen it.

**Closed by EdsonBueno** 2021-10-17 19:50 UTC
